spring :
  datasource :
    url : jdbc:postgresql://localhost:5333/bank
    username : user
    password : user
    driver-class-name : org.postgresql.Driver

  security :
    secret-key : secretkey

  liquibase :
    change-log : classpath:liquibase/changelog-master.xml
