version : "3.8"

services :

  tomcat :
    image : tomcat:10.1
    container_name : tomcat
    environment :
      - JPDA_ADDRESS=*:8100
      - JPDA_TRANSPORT=dt_socket
    command : ["catalina.sh", "jpda", "run"]
    volumes :
      - ../atm/build/libs/:/usr/local/tomcat/webapps/
    ports :
      - 8080:8080
      - 8100:8100
