version : "3.8"

services :

  tomcat :
    image : tomcat:10-jre11
    container_name : tomcat
    environment :
      - JPDA_ADDRESS=*:8100
      - JPDA_TRANSPORT=dt_socket
    command : ["catalina.sh", "jpda", "run"]
    volumes :
      - ../atm/build/libs/atm.war:/usr/local/tomcat/webapps/atm.war
    ports :
      - 8080:8080
      - 8100:8100

  database :
    image : postgres
    container_name: postgres
    restart : always
    volumes :
      - ../atm/src/main/resources/db/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql:ro
      - ../db-data:/var/lib/postgresql/data
    environment :
      POSTGRES_PASSWORD : 123qwe
    ports :
      - 5432:5432